### ISSUE TITLE
Allow reduction of precision for remainingAttendeeCapacity

### ISSUE THREAD

**Issue by nickevansuk** [openactive/modelling-opportunity-data#109]
## Proposer

Fusion Lifestyle, Everyone Active

## Use Case

Leisure operators are sensitive to the number of available spaces in classes being used for benchmarking. They would prefer to only include a "minimum spaces" value, e.g. >4 spaces, to reduce the granularity of the data available.

Note that most other types of provider are not sensitive to this data being made available, and are happy with the existing `remainingAttendeeCapacity` property.

See also the [previous discussion in beta](https://github.com/openactive/ns-beta/issues/9).

## Why is this not covered by existing properties?

`remainingAttendeeCapacity` only accepts an Integer type.

## Please provide a link to example data

`"beta:availability": ">4",`

## Proposal

In keeping with ageRange moving away from properties with micro-syntax to explicit ranges, suggest that `remainingAttendeeCapacity` also simply accepts a value of type `QuantifiedValue`.

## Example

```
{
  "@context": "https://www.openactive.io/ns/oa.jsonld",
  "type": "Event",
  "maximumAttendeeCapacity": 30,
  "remainingAttendeeCapacity": {
     "type": "QuantifiedValue",
     "minValue": 4
  }
}
```

**Comment by nickevansuk** [comment]
Note that this is also a prerequisite for Legend opening data

**Comment by iaindowns** [comment]
does this mean that remainingAttendeeCapacity can have either a number of a complex record?

What are the options for type and values?

**Comment by nickevansuk** [comment]
Update from Legend customer workshop: this was not viewed as important.

Update from Gladstone work: this is not currently included in OWS.

**Comment by nickevansuk** [comment]
Closing this issue as the Open Booking API requires `remainingAttendeeCapacity`, and everyone in the ecosystem is now publishing this data and happy doing so
