### ISSUE TITLE
facilityUse missing

### ISSUE THREAD

**Issue by nickevansuk** [openactive/modelling-opportunity-data#112]
oa:IndividualFacilityUse should have a facilityUse property which is the inverse of the individualFacilityUses property of oa:FacilityUse 

Also oa:Slot is missing oa:individualFacilityUse

**Comment by ldodds** [comment]
We could add the first property, will review.

The second is already covered by the facilityUse property, we don't need a second property for the same relationship.

**Comment by ldodds** [comment]
Adding a `groupFacilityUse` property rather than overloading the `facilityUse` property of `Slot`.

**Comment by nickevansuk** [comment]
@ldodds given that "groupFacilityUse" doesn't follow any schema.org conventions in the name, can I propose a more radical `AggregateFacilityUse` type (instead of just `FacilityUse`), so this property can be named `aggregateFacilityUse`.

This also makes is much clearer what's going on!

**Comment by nickevansuk** [comment]
(wrong button sorry!)
