### ISSUE TITLE
Protecting Personal Data in feeds

### ISSUE THREAD

**Issue by nickevansuk** [openactive/modelling-opportunity-data#114]
## Proposer

EMD

## Use Case

Personal data included in OpenActive feeds cannot always be presented under an open license, due to GDPR constraints, even if that same data is available in the public domain on the provider's own website. Specifically `Person` objects (often `leader`), are often constrained in this way.

There are cases where reuse of such personal data is allowed under "[legitimate interest](https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/lawful-basis-for-processing/legitimate-interests/)" with broad permission from the business-owning data subject, but these are often heavily constrained to organisations where there is a Data Processing Agreement in place.

Where a data user has signed a specific agreement with the data publisher, it should be possible to match the agreement signed with the data available in order that such data is displayed.

For example, on EMD's own booking system, regarding business contact details to help participants get in touch with instructors:
- [ ] Do not share my name, photo and phone number
- [X] Share my name, photo and phone number with EMD's [trusted partners]()
- [ ] Make my name, photo and phone number openly available for anyone to access use and share

## Example data

```javascript
"leader": { 
          "type": "Person",
          "name": "Alex Smith",
          "jobTitle": "Centre Administrator",
          "telephone": "07813 333331",
          "gender": "http://schema.org/Male",
          "image": "https://www.example.com/profile-photo/of-person.jpg"
        }
```

## Proposal

Two alternative approaches following initial analysis:
- Restrict sensitive data to a private API so as to restrict its use to only those who are permitted to reuse it, and markup this data within the API to differentiate it
- Clearly mark specific properties as excluded from the license in the open feed - noting that not all fields in an object need to be excluded, e.g. leader.gender. 

As the data is already in the public domain (on the website), the restricting access to the data via technical means is not legally necessary, providing the license is clearly marked. However making the data so readily accessible might encourage unlawful use.

## Straw man example: Specify a license for reuse

If a data user has been approved at "https://emduk.org/personal-data-reuse/", then they may use the fields specified, and string-match licenseRequired against their own list of signed data processing licenses/agreements.

```javascript
"leader": { 
          "type": "Person",
          "name": "Alex Smith",
          "jobTitle": "Centre Administrator",
          "telephone": "07813 333331",
          "gender": "http://schema.org/Male",
          "image": "https://www.example.com/profile-photo/of-person.jpg",
          "licenseCaveat": {
            "type": "FieldSpecificLicenseRequirement",
            "propertyTarget": ["name", "telephone", "image"],
            "licenseRequired": "https://emduk.org/personal-data-reuse/"
          }
        }
```

**Comment by ldodds** [comment]
From [our post](https://blog.openactive.io/privacy-by-design-what-gdpr-means-for-your-open-opportunity-data-b1f5a805e1e6):

> Some coaches or session leaders may wish to publish and share information about themselves, but we think this should only be done if they have given consent.

From the spec:

> Applications must not publish personal data without permission
> ....

If the user hasn't given consent for the information to be included in the data feed, then it shouldn't be included. People can also withdraw consent at any time. 

This isn't really about open licensing, its about implementation of the GDPR. The exact same situation applies any time that data is being shared, whether in open data, a private API, or publicly on the EMD website. People can exercise their rights at any time. There are no licensing options that will remove someone's rights to do this. 

You can't just include sensitive information in a feed without permission.

EMD could consider offering a private API, but they will still need to work through all of the issues around offering and gaining consent, exercising of rights, clarifying data sharing arrangements with the individuals and partners, etc.
