### ISSUE TITLE
Poly-hierarchical list 

### ISSUE THREAD

**Issue by nickevansuk** [openactive/modelling-opportunity-data#125]
## `broader` and `narrower` properties should both be defined as arrays

The `broader` and `narrower` properties should both be defined as *arrays* in the upcoming 2.0 profile, to ensure that no breaking changes are required later.

As per previous discussions, `inScheme` can be an array only in some contexts, but this can be added in 2.1 as part of https://github.com/openactive/modelling-opportunity-data/issues/124 without creating a breaking change.

![screen shot 2018-09-12 at 00 20 32](https://user-images.githubusercontent.com/2616208/45392985-ba441480-b621-11e8-97c0-d33fe6224af8.png)

## Make spec example consistent with usage in published activity lists
Ideally we'd also include another ConceptScheme example in the spec which uses "broader" instead of "narrower" to align with the actual master activity list, and to show how a poly-hierarchical list is defined.
## Examples of this in action

See here for the new "contributor's fork" list, and its use of Broader as an array for the poly-hierarchical list (e.g. look at `0771fcb2-b5f7-4247-8d54-90648c839d46`): https://github.com/openactive/activity-list/blob/ea1e0bcb51d6f83f84ed4fe5ccbcf5c2a44d2494/activity-list.jsonld

```
{
  "@context": "https://www.openactive.io/ns/oa.jsonld",
  "type": "ConceptScheme",
  "id": "http://www.example.org/activity-list",
  "title": "Activity List",
  "description": "An example activity list",
  "concept": [
    {
      "id": "https://openactive.io/activity-list/#984068a7-5b7b-4989-bb33-f96953d8960c",
      "type": "Concept",
      "notation": "group_exercise",
      "prefLabel": "Group Exercise",
      "topConceptOf": [ "http://www.example.org/activity-list" ]
    },
    {
      "id": "https://openactive.io/activity-list/#d3b5104a-2e31-4cca-a278-ef8e0987a764",
      "type": "Concept",
      "notation": "dance_fitness",
      "prefLabel": "Dance Fitness",
      "broader": [ "https://openactive.io/activity-list/#984068a7-5b7b-4989-bb33-f96953d8960c" ]
    },
    {
      "id": "https://openactive.io/activity-list/#20532927-bb47-4bdf-b341-4966336baf11",
      "type": "Concept",
      "notation": "azonto_fitness",
      "prefLabel": "Azonto Fitness",
      "broader": [ "https://openactive.io/activity-list/#d3b5104a-2e31-4cca-a278-ef8e0987a764" ]
    }
  ]
}
```

**Comment by nickevansuk** [comment]
@ldodds suggest even if example not included that `broader` be defined as an array. See comments here: https://docs.google.com/spreadsheets/d/1jpw-cSdKygBF5UXIAYvrurkXRe8mu-sPClVb5yrMtPc/edit

**Comment by ldodds** [comment]
Updating spec to use arrays
