### ISSUE TITLE
organizer required field

### ISSUE THREAD

**Issue by nickevansuk** [openactive/modelling-opportunity-data#134]
Context: `organizer` may used to determine if an Event credible (based on whether the organizer is known / verified), and to filter for such credible Events.

@nickevansuk: `organizer` should be required, as there is always a person or organisation ultimately responsible for organising a particular event.

@ldodds: In the case of this being a Person, because we allow name and other information to be optional, then we'll end up with effectively empty Person objects in feeds just to comply ...

@nickevansuk: Suggest in the rare case that organizer is set to a `Person`, that object must have at least a `url` or `id` set. Ideally Events should not be published without a (hopefully credible, or at the very least verifiable) organizer referenced, otherwise it becomes difficult to "approve" a large number of Events for display as a data consumer without considering each individually.

**Comment by ldodds** [comment]
OK, lets go with making it required rather than recommended.

However I don't think we should add any further conformance rules around Person.
