### ISSUE TITLE
Event subTypes do not inherit required/recommended field status

### ISSUE THREAD

**Issue by nickevansuk** [openactive/modelling-opportunity-data#138]
startDate and endDate are not required or recommended on SessionSeries (they don't mean anything at that level), and if they are present on SessionSeries they should be dates only (they should not include a time component).

The [example](https://www.openactive.io/modelling-opportunity-data/EditorsDraft/#regular-sessions-sessionseries-and-scheduledsession-) in the spec shows this, however as @petewalker points out, "It doesn't say anywhere in the spec that the required / recommended status of startDate or endDate varies for any of the event types."

This should be clarified.

**Comment by petewalker** [comment]
Additionally, the example @nickevansuk links to is a little wrong:

* It has a `type` of `ScheduledSeries`, not `SessionSeries`
* The name is `Wednesday Yoga`, but the description mentions aquathlon!

**Comment by nickevansuk** [comment]
To expand the scope of this issue to cover all situations where "required / recommended status of startDate or endDate varies for any of the event types":

- Required / recommended status is NOT inherited by subTypes (ever?)
- Event MUST have a startDate, or an eventSchedule, _or a subEvent_.
- SessionSeries MUST have an eventSchedule or a subEvent.
- ScheduledSession MUST NOT have either a eventSchedule or a subEvent.
- ScheduledSession MUST have a startDate.
- HeadlineEvent MUST have a startDate (which may just be a date, not a datetime)
- startDate and endDate are not required or recommended on SessionSeries (#186 (comment))

**Comment by nickevansuk** [comment]
Further criteria from https://github.com/openactive/data-model-validator/issues/217 to consider:

- description, image, organiser, ageRange, genderRestriction, level should not be recommended on ScheduledSession (that detail should be held at SessionSeries)
- url on ScheduledSession is just recommended not required.
- eventStatus should not be recommended on SessionSeries, but should be recommended on ScheduledSession

**Comment by ldodds** [comment]
re: "Required / recommended status is NOT inherited by subTypes (ever?)" I'm not sure about applying this as a general rule across the board, but perhaps for specific subTypes.
