### ISSUE TITLE
priceCurrency should not be required if the Offer has a zero price

### ISSUE THREAD

**Issue by petewalker** [openactive/modelling-opportunity-data#140]
Noted here: https://github.com/openactive/data-model-validator/issues/158#issuecomment-418077538

In accordance with https://github.com/openactive/open-booking-api/issues/54 in order to be consistent with the Booking API spec, the `priceCurrency` of an `Offer` should not be required when the `price` is zero.

**Comment by ldodds** [comment]
This is in the editors draft now. However I've added a conformance rule to check that the currency is specified if the price > 0.
