### ISSUE TITLE
schema:SessionSeries must have either a subEvent property and/or an eventSchedule

### ISSUE THREAD

**Issue by petewalker** [openactive/modelling-opportunity-data#145]
Inline with the rules spreadsheet, the following should be added to the proposal:

>A `schema:SessionSeries` MUST have either a `subEvent` property AND/or an `eventSchedule` property that provides information about the individual sessions.

**Comment by ldodds** [comment]
Note that this is inconsistent with #158 which @nickevansuk has proposed.

This would mean it would be legal for a Session series to not have an `eventSchedule` or a `subEvent` if its referenced from a `superEvent` property in a feed.

I can add some generic wording to the spec that allows for both, but the validator may need to be cleverer to understand that extra context.

So broadly, a `SessionSeries` must have either an eventSchedule AND/OR be explicitly associated with a list of `ScheduledSession`s via either the `subEvent` or `superEvent` properties. That's correct in terms of the general model I think.
