### ISSUE TITLE
Simplify to single organizer

### ISSUE THREAD

**Issue by nickevansuk** [openactive/modelling-opportunity-data#146]
The previous version of the specification included the following definition for `organizer`: "`The person or organization ultimately responsible for an event.`" e.g:
  ```
    "organizer": {
      "type": "Organization",
      "name": "Central Speedball Association",
      "url": "http://www.speedball-world.com"
    }
  ```

The candidate spec includes a looser definition: "`One or more people or organizations responsible for running an event.`" e.g:
  ```
    "organizer": [
      {
       "type": "Organization",
       "name": "Central Speedball Association",
       "url": "http://www.speedball-world.com"
      }
    ]
  ```

Having reviewed this thoroughly, there are several compelling reasons to not add such complexity at this stage, and for the spec to mandate a single organizer instead of an array.

Reasons for having a single organizer:

- **Value in specificity**: There is value in the current definition which is currently being relied upon (see below). In general a theme of 2.0 was to increase specificity rather than reduce it.
- **Lack of support**: Having looked through all existing examples, and at other data sources online, I have struggled to find any examples of an event with more than one organiser. Even when GoodGym events are run in partnership with another organisation, "GoodGym" is still the primary organiser. The issue with this being such an edge case is that it's unlikely to be well supported by data consumers anyway - as all current data, and all data I could find, has a single organiser, why code for the edge case.
- **Legal**: From the legal perspective, when a booking is made the individual enters into a contract with the organizer. Even with co-branded events there is a primary host who would be considered liable if there were any issue. The organizer is effectively the "seller" in the commercial relationship, and has the legal responsibility which comes with this. Even if there were a tri-party agreement as a T&Cs, arguably that would form a new organizer: "Ben and Jerry", instead of ["Ben", Jerry"]. Note that on [booking pages](https://checkout.getactivelondon.com/v1/events/fusion-GL1SSOF06000418#/details), confirmation e-mails, etc for brokers the organizer must be clearly displayed for legal and tax reasons, to make it clear which legal entity is the "seller" of the service, and to ensure that they broker is not considered the "seller" and does not assume full liability of the "seller". Having an array creates further issues with this: who is the primary organizer? Who should be displayed? Two organizations cannot both be the "seller", as the contract and terms only involve two parties ("buyer" and "seller").
- **Implementation simplicity**: Having an array of organizers creates complexity in all downstream systems: in user experience, indexing, and processing.
- **Limits further uses**: Having an array of organizer makes it more difficult to use Organization for things like service/termsOfService, tax rate, etc, which would naturally fit in there (as the Organization is providing the service legally and is the corporate entity with which any transaction takes place). For example: Which organizer would the end user call if there are issues with the event or to request a refund? Again suggest we need to find practical examples of this to model against.

Given the above, I suggest that although there might be an edge case in the future where multiple Organizations are involved in hosting an event, these should be looked at closely when we have visibility of them, and multiple routes explored to accommodate the requirement: e.g. allowing `contributor` to also be of type `"Organization"`.

Even if a future version of the spec allowed an array as well as a single value for `organizer`, that next version would have all stakeholders around the table to agree on whether to _also_ support an array, or some other option. Supporting an array in addition to a single value is still simpler in overall complexity imho, as the 99% case can have the legal issues above handled simply, and data consumers can simply ignore handling the 1% if they are just focussing on an MVP.

**Comment by ldodds** [comment]
OK, lets go with single organizer. The change to an array was largely motivated by consistency with some similar properties, but you make a good point around scope of existing data, responsibility, etc. 

Will not however that no-one should be driving legal liability decisions off the structure of this data.
