### ISSUE TITLE
AggregateFacilityUse

### ISSUE THREAD

**Issue by nickevansuk** [openactive/modelling-opportunity-data#148]
@ldodds given that "groupFacilityUse" doesn't follow any schema.org conventions in the name, can I propose a more radical `AggregateFacilityUse` type (instead of just `FacilityUse`), so this property can be named `aggregateFacilityUse`.

Consistent with `AggregateOffer` and `AggregateRating`.

This also makes is much clearer what's going on!

**Comment by nickevansuk** [comment]
@ldodds worth discussing via high bandwidth means? Better get it in now as breaking change

Matches our approach with SessionSeries and SecheduledSession of making the use of the type explicit

**Comment by ldodds** [comment]
I'm not a fan of the name, or of changing this unnecessarily.

**Comment by nickevansuk** [comment]
Could we at least change to "aggregateFacilityUse"? We don't have groupX for anything else?
