### ISSUE TITLE
Missing SKOS vocabulary for describing disability support

### ISSUE THREAD

**Issue by nickevansuk** [openactive/modelling-opportunity-data#165]
## Issue
Feedback via Sport England: Disability Rights UK, had heard through the British Paralympic Association about OpenActive and that currently: “the standardised form that was being developed has a tick box for ‘accessible’ but no other way of breaking down what ‘accessible’ means (wheelchair, visually impaired, hearing impaired, autism friendly etc)”

## Investigation
In May 2017 it was agreed in a W3C Community Group meeting that we should create:
> “a small controlled vocabulary of terms for describing disability support, based on the current commonly used terms, e.g. Physical Impairment, Hearing Impairment, etc. These will have clear descriptions, to encourage consistent use” (https://lists.w3.org/Archives/Public/public-openactive/2017May/0014.html)

(For reference, the whole discussion can be found here: https://youtu.be/fIT3W00pwP4, along with the then [current commonly used terms](https://docs.google.com/spreadsheets/d/1ubFqCqmrbwBFOVtYKQ_OCY2NGtMn5ZguuSAyjxehifI/edit?usp=sharing) spreadsheet that was presented).

Although agreement was reached, the subsequent action https://github.com/openactive/modelling-opportunity-data/issues/26, was not completed, likely due to a change in priority, and we do not currently have a controlled vocabulary for this.

Looking at the currently published data, the original conclusion reached is still valid.

### Steps

1. Create the vocabulary at https://openactive.io/accessibility-support which meets the requirements previously identified.

2. Recommend the use of this vocabulary as part of Modelling Specification 1.0.

### Content

Suggested list below (based on previous work):

- `Visual impairment`
- `Hearing impairment`
- `Physical impairment`
- `Learning impairment`
- `Mental health issues`

The beauty of the vocab is that even if we refine the preferred labels of the above, there seems to be very good agreement on the concept behind each of these being relevant.

**Comment by nickevansuk** [comment]
To save time tomorrow with review, I have just created an MVP of this vocabulary with the contents above and the relevant routing: https://www.openactive.io/accessibility-support/

**Comment by Jadecation** [comment]
This nearly work for us, and we would use it as we are publishing and consuming this data. We have been using a list that matches this in our data collection (plus the additional below) and sharing with partners such as GLA (Mayor's Office) and Sport England as part of our reporting. 

We would say that you also need to include 'Social or Behavioural Problems' as this is a new category that has been added and generally accepted by the authorities in this area over the last few years. We added it about 2 years ago after consulting with EFDS (Activity Alliance) and Equality in Sport.

**Comment by nickevansuk** [comment]
On this basis I propose that we add the additional "Social or Behavioural Problems" term as you've suggested to the new list https://www.openactive.io/accessibility-support/, keeping this OpenActive list to help catalyse convergence amongst publishers (as it matches data published to date), but that we hold off recommending conformance to the list as a formal part of the specification until we have all parties on another W3C call to discuss this along with https://github.com/openactive/modelling-opportunity-data/issues/166 and https://github.com/openactive/modelling-opportunity-data/issues/67.

Also noting that 1.0 does not include a formal recommendation around conforming to the activity list, so this approach is consistent with that.

**Comment by ldodds** [comment]
Just to note that we're not mandating conformance to any controlled vocabularies at the moment. I plan to update the 2.0 draft to note that the working group may create additional controlled vocabularies. Their creation, adoption and improvement shouldn't require us to keep changing the data model specification.

**Comment by ldodds** [comment]
@nickevansuk on the basis that there's a draft published, should we close this issue? Feedback on that can be covered in the other repo?

Would be good to add some status indicator, links to github issues, etc on the page you've put up.

**Comment by nickevansuk** [comment]
Yep sounds good to me! Will add to other page.
