### ISSUE TITLE
Vat status of offer prices...

### ISSUE THREAD

**Issue by jeremyswright** [openactive/modelling-opportunity-data#246]
Hi,

How do I describe the Vat status of an offer? i.e. incl or excl

I'm using the php models and I'm getting a call to undefined setter method exception if I just try to provide another 'includeVat' element.

How do I just include additional data elements?

Thanks

**Comment by nickevansuk** [comment]
You're looking for `taxMode` in the `organizer`, see https://developer.openactive.io/data-model/types/organization.

An example would be:
```json
        "organizer": {
          "@type": "Organization",
          "@id": "https://id.bookingsystem.example.com/organizers/1",
          "name": "Everyone Active",
          "url": "https://www.everyoneactive.com/",
          "logo": {
            "@type": "ImageObject",
            "url": "https://s3-eu-west-2.amazonaws.com/prod-everyoneactive-wp/wp-content/uploads/2017/10/26092236/Ea-Image2.jpg"
          },
          "email": "customerservices@gll.org",
          "telephone": "01455 890508",
          "sameAs": [
            "https://www.facebook.com/everyoneactive/",
            "https://twitter.com/everyoneactive"
          ],
          "taxMode": "https://openactive.io/TaxNet"
        },
```

See here for a description of the two different modes:
https://openactive.io/open-booking-api/EditorsDraft/#tax-mode

Note that for a particular `organizer` / `seller`, the `taxMode` must always be consistent i.e. **all** their prices across all your feeds must either include or exclude VAT according to the specified `taxMode`, the taxMode can't be set at the opportunity or Offer level.

Does that help?

**Comment by jeremyswright** [comment]
That's what I needed to know, yes.

Many thanks.
