### ISSUE TITLE
New Property > Event Video / Embed Video URL

### ISSUE THREAD

**Issue by charlieclarke5** [openactive/modelling-opportunity-data#257]
If you are filing a proposed change, e.g. a new property or revised definition, then please fill in the below template.

**## Proposer**
Charlie Clarke / Kevin Flinton

**##Organisation(s) proposing:**
Playwaze / 24 Fit Local

**## Use Case**
Kevin’s research to date suggests a portion of his future users (social prescribers, link workers, and their participants) value seeing an activity in the form of a video more so than just an image before knowing it is appropriate for them. There is something powerful about seeing people like you enjoy an activity that would also be suitable for you as a way to entice and make you feel more at ease about getting involved.
 
In the standards we currently have an Image URL to work with from a publisher perspective. I sense a difficulty in data integrity if this were expanded to video; Video Embed URLs would vary between platforms like YouTube and Vimeo – I’m sure that could be got around – while some might only provide a Video URL where it is hosted, meaning it would only be clickable, not embedded – not necessarily end of the world but a little disjointed from a user journey perspective as they’d then need to go back to the search.

**## Why is this not covered by existing properties?**
Current properties only includes an image url.

**## Please provide a link to example data**
Not currently collecting, but the intention would be to display as part of a activity listing instead of as alongside an image. Image may be used for preview, embedded video used for more information alongside schedule info and other details.

**## Proposal**
Event Video or Embedded Video URL. We believe there would need to be definition about the URL type (hosted vs embedded url) so that it is easier to use and handle differences on the frontend.

**## Example**
A YoutTube video, as an example, could have two possible references; I have used the OA video as an example. 
(1) Browser URL: https://youtu.be/a2FdmspmCNk
(3) Embed iframe snippet: <iframe width="560" height="315" src="https://www.youtube.com/embed/a2FdmspmCNk" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by charlieclarke5** [comment]
@thill-odi 

"Finally, an answer. While obviously this would be pending discussion, my instinct in the first instance is to say that we should add schema:video to OpenActive Events, and then make the type for this schema:VideoObject (https://schema.org/VideoObject). This gives us all the attributes we need for either simply pointing to a URL or for dealing with embeds.

For immediate implementation this will be slightly awkward, as this will have to be done as a beta property and none of our tooling will perform strong validation upon it. However, it will get the job done.

I'll add this for discussion to the W3C agenda. You may wish to hold off on implementation until after discussion is complete - but this seems to me the likely shape of any solution."

**Comment by nickevansuk** [comment]
Great to surface this requirement again!

This property is already in beta, exactly as described above (https://openactive.io/ns-beta#video). It has been implemented by existing publishers, and can also be found in the docs (https://developer.openactive.io/data-model/types/sessionseries)

See existing discussion: https://github.com/openactive/modelling-opportunity-data/issues/88

**Comment by chrisnorfield** [comment]
Just adding my support to this. It's something we've heard anecdotally from social prescribers and found useful in other work with consumers. Great to see the property is already in beta and we'd be happy to support testing of this (Open Sessions / Get Active)

**Comment by thill-odi** [comment]
Okay, thanks for the catch @nickevansuk. The point is then to get this into 2.1. I'll close this as a duplicate, but add a link in #88.
