### ISSUE TITLE
Clubs information as open data. 

### ISSUE THREAD

**Issue by tommarley148** [openactive/modelling-opportunity-data#295]
After speaking to various AP's and other promoters of sport and PA it has become clear that there is a requirement (within the OpenActive framework) to be able to access club data. 

Which organisation(s) are proposing this issue? Herts Sports Partnership, Together Active, Active Essex.

## Use Case

A user to be able to find local club 'opportunities' which could be a membership offer, a taster session etc. This falls outside of facilities and sessions standards and is more similar to places. It needs the CTA to be flexible as the 'offer' will look different across clubs. Maybe limit them to a few such as 'join' 'try out' etc?

Club name
Location
Contact details
CTA (flexible)
Price (may not always make sense - has to be related to the CTA)
Time/Date (joining a club for example will not have a start/end time/date)
Etc

**Comment by nathansalter** [comment]
Hi Tom,

An interesting proposal, but could you provide some more information as to why this doesn't fit into existing event types, such as https://openactive.io/modelling-opportunity-data/#headline-events-headlineevent- ?

**Comment by tommarley148** [comment]
Yes - good point. I wasn't too aware of headline events within OA. How do we handle the no start time/date problem within this structure? I would be all for using this if possible.

**Comment by nathansalter** [comment]
Just to point out, things like memberships are out of the scope of this document: https://openactive.io/modelling-opportunity-data/#scope that's not to say that we might want to create a specification for this in the future, but I don't think it's currently planned.
