### ISSUE TITLE
Define additional Event properties

### ISSUE THREAD

**Issue by ldodds** [openactive/modelling-opportunity-data#3]
Schema.org doesn't currently have general terms to cover the following ways to categories [events](https://www.openactive.io/modelling-opportunity-data/#events-and-sessions): 

* Restrictions: e.g. gender, age, membership restrictions
* Suitability: e.g. level of fitness, experience 
* Pre-requisites: e.g. membership, equipment needed
* Categorisation: e.g. intensity of session, activities involved, programme followed

We should work to define these within Schema.org

**Comment by MikeThacker1** [comment]
Properties to consider (and maybe reject) are:
- data publisher
- last updated date
- commissioned by (programme may give this)
- contact - Is this just the contact details of the organiser (ie not event specific)?
- review - Any reference to independent reviews of teh activity

**Comment by ldodds** [comment]
From Nick Evans:

>In Active Lives we capture Setting, which describes where the activity is taking place - I.e. is it indoor or >outdoor? There is then a set of defined settings that you could allocate to the location, e.g. Indoor >examples are shown below:
>         At Home
>         Leisure/Fitness/Sport Centre or Gym
>         Community Centre or Village Hall
>         Specialist Facility

Should we be capturing setting as a descriptive property of an event? If so, then we should recommend a set of legal values. This would make it easier to filter/search by settings.

Alternatively, settings could be added as tags associated with an Event. This is simpler, but is more limited.

Related is:

>Other event properties could include:
>·         Activity Style – e.g. Group, 1 to 1, Individual
>·         Activity Structure – e.g. formal or informal. Formal could include Club Training session, Coached >session, Competition, while Informal could include Holiday, Social
>·         Purpose – e.g. Leisure, Competition, Training, Commuting

From last CG call:

* Surface: e.g. astro turf, etc.

**Comment by ldodds** [comment]
At our last community hangout we decided to define a minimal set of property to help describe events, these were:

* age - to be specified as a range
* sex/gender - e.g. male, female, mixed
* height - to be specified as a range (in metric)
* weight - to be specified as a range (in metric)
* category - a general purpose way to tag an event with a category. this can encompass many of the other requirements for now. After experience with seeing how it is used, we can define additional more specific properties and, if necessary, controlled vocabularies

**Comment by ldodds** [comment]
Done. Defined in the Editors Draft schema and the vocabulary at https://www.openactive.io/ns/
