### ISSUE TITLE
http://schema.org/typicalAgeRange vs oa:ageRange

### ISSUE THREAD

**Issue by nickevansuk** [openactive/modelling-opportunity-data#39]
Just interested in the rationale behind this... Why have created a new property oa:ageRange, and what's the difference from typicalAgeRange (also on an Event)?

**Comment by ldodds** [comment]
I felt that the definition of the Schema.org property wasn't quite right. "typical expected age range" seemed looser than what we wanted to specify, which was a min/max age range.

As we were also defining property for weight/height/etc I went with defining properties for our own needs for consistency.

I'll take a note to add some kind of equivalence between our property and theirs

**Comment by ldodds** [comment]
I've defined our property as a subPropertyOf of the Schema.org version so keeps some equivalence.
