### ISSUE TITLE
Decide how to publish controlled vocabularies

### ISSUE THREAD

**Issue by ldodds** [openactive/modelling-opportunity-data#4]
For the additional event properties #3 we will need some controlled vocabularies. These may be published by individual publishers or defined across the sector.

We need to decide how to publish these vocabularies, ideally following SKOS and in line with [External Enumerations](https://www.w3.org/wiki/WebSchemas/ExternalEnumerations)

**Comment by MikeThacker1** [comment]
Reference SKOS items in "schemes" (ie URI sets) referenced with their base URIs.

Eg "Circumstance" URIs from http://id.esd.org.uk/list/circumstances might be used to define "Restrictions" on individuals that might book/attend.

Allow any scheme but identify some suitable ones..

(There are still eligibility types that do not refer to the type of person, eg residence, referral, membership.  And ideally these might be combined with AND and OR operators.)

**Comment by ldodds** [comment]
Keeping within the current plan of building against Schema.org, I think we can publish vocabularies using the enumerated value support outlined here: schemaorg/schemaorg#894. This aligns with SKOS.

**Comment by ldodds** [comment]
For the first version of the specification we won't be publishing any new controlled vocabularies, so I'm closing this issue for now.

I expect that in future we'll use SKOS to publish these lists and reuse existing terms and vocabularies wherever possible.
