### ISSUE TITLE
Proposal: modelling of facilities

### ISSUE THREAD

**Issue by ldodds** [openactive/modelling-opportunity-data#62]
We need to add support for facilities to the Modelling Opportunity Data specification.

# Proposal

We've identified the following use cases to support adding facilities (e.g. squash courts, pitches, table tennis tables):

* What facilities are available at a location?
* What activities can be carried out in this facility?
* How do I find this specific squash court? 
* What dates and times can I book this squash court?
* Is this squash court still available at a given time?

Modelling the spatial relationship and configuration of facilities within leisure centres is complex. For example the same sports hall can be used in different configurations. Capturing these details are not important for our primary use cases. An end-user booking a squash court does not need this detail.

Similarly, an end-user booking a court or table tennis table needs to know which leisure centre to turn up to, but they don't need to know exactly which court or table they will be using. They are interested in booking a facility for a period of time.

Finally, an end-user is not really interested in the difference between fixed facilities vs equipment like table-tennis tables that might be moved around a location. They're just interested in booking a space to take part in a physical activity.

Our proposed approach is to treat the availability of a squash court or pitch as a [product](http://schema.org/Product) that is being offered by the leisure provider.

We plan to call this product a __Bookable Facility__.

## Describing a Bookable Facility (Product)

We need to be able to capture the following information:

* name, title, description, images and other descriptive information
* the facility that is being booked via a [location](http://schema.org/location) property
* the availability of the facility (see below)
* the price for booking the facility, via an [offers](http://schema.org/offers) property
* the type of activity that the facility covers, via the existing `activity` property. This will allow an application to filter our Bookable Facilities that aren't associated with, e.g. squash or football.

### Availability of a Bookable Facility

We propose to handle the availability of a facility by treating the "slots" in which it can be booked, as a series of [Events](http://schema.org/Event). For example, a list of 30 minute events can describe the availability of a table tennis table over the course of a day.

This allows us to use the existing features of the data model to describe events, event schedules and event availability.

We will however need to define two new [EventStatusTypes](http://schema.org/EventStatusType) to say that a slot is Available or Booked. The existing Schema.org list of statuses doesn't cover that use case.

## Describing the facility a user is booking

In the current opportunity model we say that fixed facilities, like squash courts or swimming pools are [Places](https://www.openactive.io/modelling-opportunity-data/#places). 

So where we do need to describe the location being booked, we can use the existing data model.

We may need to capture some additional attributes of facilities, e.g. "indoor" or "outdoor". Or types of pitch. 

## Questions

1. Are there other use cases which we haven't recorded?
2. Is "Bookable Facility" a good name? (If not, then please provide a suggestion)
3. Is there other information about a Bookable Facility we should be recording?
4. Does the suggested approach to describing availability seem reasonable?
5. What information might we need to capture about the facility that a user is booking?

**Comment by ldodds** [comment]
We should consider adding surface types and whether there are flood lights as specific properties

**Comment by ldodds** [comment]
Other things to consider:

* formats, e.g. cricket, cricket nets; five-a-side
* equipment rental
* car parks and changing rooms

**Comment by ldodds** [comment]
The offers should be part of the events, to cover peak/off-peak pricing

**Comment by ldodds** [comment]
Use of `addOn` to describe additional equipment hire, etc http://schema.org/addOn

`businessFunction` to say if something is being leased or bought http://schema.org/businessFunction

**Comment by ldodds** [comment]
Update to the proposal:

* Will call the product `AmenityUse` rather than `BookableFacility`
* Offers can be attached to the product (for single pricing models) or individual events (for peak/variable pricing)

TODO list of things to add to vocabulary:

* [ ] `AmenityUse` type
* [ ] `activity` can be applied to `AmenityUse` and not just `Event`
* [ ] Add two new `EventStatusType` for Available and Unavailable
* [ ] Add `format` to `AmenityUse`
* [ ] Add `surface` to `SportsActivityLocation`

**Comment by jamiefoale** [comment]
Hi Leigh,

Have just had a look through and have the following thoughts based on my experience at MyLocalPitch:

- We wouldn't describe a facility as an amenity, we tend to describe eg changing rooms as amenities. However I'm sure there's no reason not to
- In 5.10 when describing the facility would you want to include how many facilities are available, eg if there are 7 identical 5 a side football pitches? 
- Also in 5.10 is it right to describe at facility as an 'Event'? It just doesn't seem to fit with the earlier definitions of an event in 4.3. Would 'Slot' be a better description of the type?
- Within the startDate there is no timezone statement, eg we use 'Z' but I see '-05:00' elsewhere in the spec
- Would it be sensible for a slot to have a slot ID, e.g. for when a booking is made?

Jamie

**Comment by ldodds** [comment]
@nickevansuk @jamiefoale re: use of the term "amenity", I was trying to find a phrase that covered both facilities and equipment, i.e. something at a location that is available for use. The definition of amenity I was referencing was "a desirable or useful feature or facility of a building or place." which seemed to fit. But, yes there are other uses of the term. 

Are there other concrete suggestions on naming?

I'm reluctant to use something like "FacilitiyUse" as it doesn't clearly indicate that we're thinking about equipment. 

Alternatively, we could define two types: "EquipmentUse" and "FacilityUse" both of which are Products.

**Comment by ldodds** [comment]
@jamiefoale to answer your other questions:

* In 5.10 when describing the facility would you want to include how many facilities are available, eg if there are 7 identical 5 a side football pitches?

What do you think is best? My assumption was that the user just wants to know there's a pitch available at a specific time. Behind the scenes the platform can handle if there's just one or several options.

If there's a need to list each one, then they can be published as a separate products.

* Also in 5.10 is it right to describe at facility as an 'Event'? It just doesn't seem to fit with the earlier definitions of an event in 4.3. Would 'Slot' be a better description of the type?

The facility isn't an Event. There's a product which is offering use of a facility at some set times. So the list of events are the "slots".

* Within the startDate there is no timezone statement, eg we use 'Z' but I see '-05:00' elsewhere in the spec

Yes, it should be more clearly specified. Just a poor example.

* Would it be sensible for a slot to have a slot ID, e.g. for when a booking is made?

Each Event is a slot, and an event can have an identifier, so I think that is covered.

**Comment by nickevansuk** [comment]
I was about to say, isn't EquipmentUse a niche usecase here? Or are you thinking Table Tennis Table as Equipment? Potentially it's just a different kind of use of the facility (the sports hall with the table in is the facility, the equipment is secondary, the sports hall is being used used for table tennis).

My understanding was that procuring the equipment was often the responsibility of the site, rather than of the user. So you wouldn't hire a 'Table Tennis Table' and a 'Sports Hall' separately, you'd hire a 'Table Tennis Table Slot' and they would put the Table Tennis Table in the Sports Halls for you. Same with badminton nets or anything else required for the slot. So everything is FacilitiyUse?

**Comment by jamiefoale** [comment]
Being aware of the GLL example, you book a table tennis slot in the same way as a tennis court slot or football pitch slot.
There are other examples of equipment use, eg Bowling machines on indoor cricket lanes, but that would be treated separately and an adjunct to the cricket facility (and charged extra).

**Comment by jamiefoale** [comment]
@ldodds Re the quantity of facilities, I think this is fine and the simpler approach. Some publishers might want to list the quantity of facilities and the data exists in other models eg Active Places, but it can be variable and inconsistent.

**Comment by rdebourbon** [comment]
@ldodds As per my email to the list - I'm fine with the bulk of this - my primary concern would be the inclusion of availability data within the paged spec. 

In our experience, the way spaces tend to be configured is such that you land up with a series of interrelated opportunities that have overlapping schedules sold on a first come first serve basis, and the act of booking/cancelling results in a series of cascading updates to the availability data for the set of linked opportunities. If the paged dataset includes availability indicators for each timeslot, then a single booking could result in large numbers of cascaded updates to linked opportunities.

I guess it all comes down to the frequency with which the paged data is collated for publishing - the more frequently it is collated / published the more likely that single booking actions (book/cancel) will introduce "bloat" with cascaded availability updates.

**Comment by rdebourbon** [comment]
@jamiefoale @ldodds If we get into the realm of including the number of facilities per timeslot, we would probably need to account for availability of each facility as well, so as to account for the use-case where a customer is looking to see if Pitch A is available, not just any pitch. 

@ldodds I'm not convinced that having the platform produce a new product per facility would be the right approach for the case where data producers want to specifically expose each facility. I think this is an unnecessary level of indirection, and conflates the facility with the actual "product" ie 5-a-side. I'd much rather see some way of decorating the opportunity with more information around the number of facilities (either a total count, or a list of some sort)

**Comment by ldodds** [comment]
## List of revisions to make to spec:

* [ ] No longer call this `AmenityUse`. Was felt to be confusing and we're now proposing to use `amenityFeature` (see #70) so lets go with `FacilityUse` to cover all of the expected use cases including hiring of table tennis tables. Include reference to "resource".
* [ ] Offers can be attached to the product (for single pricing models) or individual events (for peak/variable pricing). If we allow this, it would be an example of Offer inheritance as noted here: openactive/open-booking-api/issues/13
* [ ] suggest `inventoryLevel` as a means of indicating number of items available for that Offer, e.g. for whole facility, individual slot
* [ ] Add a note to the specification that we acknowledge that there may be potential issues with volume of cascading of updates for some multi-use facilities. 

[We agreed](https://youtu.be/VGW8BEE5c-8?t=48m49s) to focus on the single-use use cases for now, but flag up that it may need more work later. So recognising that this might not be optimal for complex multi-use environments. Ensures we can make single-use facilities open and bookable for now.

We recognise it is not ideal for all cases, but would like to identify scale of the issue in practice, rather than over-engineer now. 

In the specification we should note that we may need to revise this area of the specification later, or explore other options, e.g. separate using separate feeds for that data, moving availability out of the feed (e.g. click through or via lookup API), or moving just schedules out into separate feeds, or streamlining updates. 

We had some discussion about this and the requirements, e.g. the ability to do availability searching across multiple locations which might require high-throughout harvesting of up to date availability vs checking availability later. But there were mixed views and requirements.

File a separate issue to track any ongoing discussions around multi-purpose facilities.

## List of things to add to vocabulary:

* [ ] `FacilityUse` type
* [ ] `activity` can be applied to `FacilityUse` and not just `Event`
* [ ] Add two new `EventStatusType` for Available and Unavailable
* [ ] Add `format` to `FacilityUse`
* [ ] Add `surface` to `SportsActivityLocation`

**Comment by ldodds** [comment]
Timezone on example
