### ISSUE TITLE
Representing the exact location of an Event within a location

### ISSUE THREAD

**Issue by nickevansuk** [openactive/modelling-opportunity-data#66]
GLL have currently used [containedInPlace](http://schema.org/containedInPlace) to represent the location in the venue where the event takes place, e.g.

```
"location": {  
  "type":"SportsActivityLocation",
  "name":"Studio",
  "containedInPlace": {  
    "type":"Place",
    "url":"https://better.org.uk/leisure-centre/hackney/queensbridge-sport-and-community-centre",
    "name":"Queensbridge Sports And Community Centre",
    "address": {  
      "type":"PostalAddress",
      "addressLocality":"Hackney",
      "addressRegion":"London East",
      "postalCode":"E8 3XW",
      "streetAddress":"30, Holly Street"
    },
    "geo": {  
      "latitude":51.5426,
      "longitude":-0.071408
    },
    "telephone":"020 7923 7773"
  }
}
```

Two issues with the above:
- This works when the Event takes place within a single space (e.g. "Studio"), however when the Event takes place in multiple spaces (e.g. multiple lanes in a swimming pool, or multiple courts in a sports hall) this is makes the representation less obvious.
- It makes the address of the Event (an important piece of data) appear at different levels within the JSON, which makes in inconsistent for data consumers.

**Comment by ldodds** [comment]
Closing, more recent discussion in #110
