### ISSUE TITLE
Proposal: ageRange revision

### ISSUE THREAD

**Issue by ldodds** [openactive/modelling-opportunity-data#68]
## Proposer

This has been raised by several data consumers

## Use Case

* as a potential participant I want to know whether I fall within the age range for an event
* as a data consumer I need to be able to accurately filter events to show users correct age ranges

## Why is this not covered by existing properties?

This is a proposed change to an existing property to revise its definition.

Our statistics on usage of the property show that any changes will only currently impact GoodGym, Fusion and GLL.

## Proposal

The current definition of `ageRange` defines it to be a string value. It is either a single number or a range, e.g. "18-55".

Feedback suggests it would be better to define explicit minimum and maximum age ranges as separate numeric values.

The proposed change is to make this a structured property that refers to a [QuantifiedValue](http://schema.org/QuantitativeValue) which will have [minValue](http://schema.org/minValue) and [maxValue](http://schema.org/maxValue) properties.

Validation rules:

* must have a `type` of `QuantifiedValue`
* at least one of `minValue` or `maxValue` must be supplied
* if `ageRange` is specified, but with no `minValue`, then there is no minimum age for the `Event`
* if `ageRange` is specified, but with no `maxValue` then there is no maximum age for the `Event`
* if there is no `ageRange` property then consumer SHOULD assume that the event is suitable for adults only. E.g. as if the `minValue` was specified as `18`

This proposal does mean that an event that is "suitable for all" must have explicit age ranges specified. This avoids any potential issues, e.g. with families being recommended events that are not suitable for all ages.

## Example

The following Event is suitable for people in the 18-55 age range:

```
{
  "@context": "https://www.openactive.io/ns/oa.jsonld",
  "type": "Event",
  "ageRange": {
     "type": "QuantifiedValue",
     "minValue": 18,
     "maxValue": 55
  }
}
```

The following event is suitable for under 16s:

```
{
  "@context": "https://www.openactive.io/ns/oa.jsonld",
  "type": "Event",
  "ageRange": {
     "type": "QuantifiedValue",
     "maxValue": 16
  }
}
```

**Comment by nickbaileyuk** [comment]
Suggest that this property is not mandatory. If it is not provided in the feed the event should be considered as suitable for all ages.

**Comment by ldodds** [comment]
@nickbaileyuk yep, its an optional property already and default is as you suggest.

An additionall requirement is to allow `ageRange` to be applied to an `Offer` as described here openactive/ns-beta/issues/11
