### ISSUE TITLE
Proposal: specifying amenities available at a Place

### ISSUE THREAD

**Issue by ldodds** [openactive/modelling-opportunity-data#70]
## Proposer

This has been raised in previous discussions, but most recently in [supporting ClassFinder in publishing their data](https://github.com/openactive/activation/issues/113). 

## Use Case

* "as a potential participant, I want to know if there are showers or changing rooms available at a location"

## Why is this not covered by existing properties?

The existing model doesn't address this requirement. It is mostly covered by terms in schema.org, but we may want to clarify their usage

## Please provide a link to example data

See example here: https://github.com/openactive/activation/issues/113

## Proposal

Schema.org allows the description of a `Place` to include a list of [amenityFeatures](http://schema.org/amenityFeature)  which is a characteristic of service available at that location. 

An amenity is described as a [LocationFeatureSpecification](http://schema.org/LocationFeatureSpecification). The basic use just indicate that a named amenity is present or absent.

For example to indicate there are changing facilities at a location:

```
{
  "type": "Place",
  "amenityFeature": [
     {
        "type": "LocationFeatureSpecification",
        "name": "Changing Facilities",
        "value": true
     }
  ]
}
```

OpenActive publishers can use this markup now to include lists of amenities without any changes to the specification.

Additional properties allow publishers to specify more information, e.g. the hours during which the amenty is available.

The downside to this is approach is that publishers are likely to use different names for the same amenity. E.g. "Changing Facility", "Changing Facilities", "Changing Room".

This proposal suggests that OpenActive define a number of types of "Location Feature Specification", which will increase consistency. 

The recommended list of initial amenities includes:

* Changing Rooms
* Showers
* Public Toilet
* Lockers
* Towels
* Creche
* Parking
* Baby Changing
* Equipment Hire
* Floodlights

Amenities not on the standard list can still be described using the above approach outlined above.

The above example would then be specified as:

```
{
  "type": "Place",
  "amenityFeature": [
     {
        "type": "ChangingRooms",
        "name": "Changing Facilities",
        "value": true
     }
  ]
}
```

The `type` provides consistency, while the `name` property allows publishers to indicate a preferred way of labelling the amenity. For example:

```
{
  "type": "Place",
  "amenityFeature": [
     {
        "type": "Lockers",
        "name": "Free Lockers",
        "value": true
     }
  ]
}
```

We don't indicate whether use of specific amenities are included when paying for an event. The intention here is to *just* describe what amenities are available.

## Questions

* Is the suggested list of types useful as a starting point?

**Comment by nickpde** [comment]
Hi Leigh
Other suggestions for the list would be:

- Cycle Parking 
- Free WiFi
- Cafe
- Vending Machines
- Spa related facilities which are common in the Virgin Active and David Lloyd:
- Spa
- Steam Room
- Sauna
- Beauty Treatments
- Massage
(The Beauty treatments/massage are almost services or activities but will have dedicated areas)

Not sure Floodlights are really an amenity, they are directly relevant to facilities and not all courts or pitches may have floodlighting at a particular place

You could also allow some form of free text around amenities to allow people to provide additional information without making it too complex, for example the "creche only operates between 9-5 weekdays" etc. We also know that security is often very important to consumers around lockers and cycle parking etc.

**Comment by ldodds** [comment]
Suggestion to remove floodlights and equipment hire initially
