### ISSUE TITLE
OpenActive namespace invalid

### ISSUE THREAD

**Issue by nickevansuk** [openactive/modelling-opportunity-data#76]
https://search.google.com/structured-data/testing-tool/u/0/ errors with "There was an invalid type in your JSON-LD" highlighting the line:

```
"@context": "https://www.openactive.io/ns/oa.jsonld",
```

Not sure if this is a bug with Google or namespace

**Comment by ldodds** [comment]
I don't believe they allow custom namespaces in their tool.
