### ISSUE TITLE
Schedule should use enum for "frequency"

### ISSUE THREAD

**Issue by nickevansuk** [openactive/modelling-opportunity-data#79]
The frequency of the schedule should be pulled from a enum.

Currently there's an inconsistency:
```
   "frequency": "weekly",
   "byDay": "http://schema.org/Wednesday",
```

**Comment by ldodds** [comment]
Its `repeatFrequency` rather than `frequency` that was accepted into schema.org. The value should be a Duration, So:

```
"repeatFrequency": "P1W"
```
