### ISSUE TITLE
Collect and publish more example activity lists

### ISSUE THREAD

**Issue by ldodds** [openactive/modelling-opportunity-data#8]
We should collect and publish [more example data about activity lists](https://github.com/openactive/w3c-cg-example-data/tree/master/activity-lists).

**Comment by alsav25** [comment]
This is a aggregator of obstacle course race (OCR) events which will link to a range of activities (running, mountain biking, swimming, triathlon) - https://www.mychallengehq.com/frontend/search/search-form
