### ISSUE TITLE
inventoryLevel and eventStatus

### ISSUE THREAD

**Issue by nickevansuk** [openactive/modelling-opportunity-data#85]
## Issue
"inventoryLevel" is in an inconsistent location compared with our recommendation for sessions, and "eventStatus" doesn't work at the "product" level of abstraction.

## Example
The example below illustrates the issues:
1. In the below example "eventStatus" and "inventoryLevel" aren't both relevant, and given this should represent a product, it will not be "unavailable" (there will just be "zero" products available).
2. If there is an "inventoryLevel" set it may not make sense to have it duplicated for each Offer, as offers are usually used for different price levels (Adult, Child, Member, Non-member etc).

```
{
  "type": "Event",
  "identifier": "B2BAD2018-03-01T10:00:00Z".
  "startDate": "2018-03-01T10:00:00Z",
  "endDate": "2018-03-01T11:00:00Z",
  "duration": "PT60M",
  "eventStatus": "http://openactive.io/ns#Available",
  "offers": [
    {
      "type": "Offer",
      "name": "Adult",
      "price": "9.50",
      "priceCurrency": "GBP",
      "inventoryLevel": 2
    },
    {
      "type": "Offer",
      "name": "Junior",
      "price": "4.50",
      "priceCurrency": "GBP",
      "inventoryLevel": 2
    }
  ]
}
```

## Suggested solution
Use inventoryLevel at the Event level instead of the offer level, to replace eventStatus

```javascript
{
  "type": "Event",
  "identifier": "B2BAD2018-03-01T10:00:00Z",
  "startDate": "2018-03-01T10:00:00Z",
  "endDate": "2018-03-01T11:00:00Z",
  "duration": "PT60M", /* duration converted to ISO spec. Can do this with System.Xml.XmlConvert.ToString(TimeSpan.FromMinutes(ClassDuration)) */
  "inventoryLevel": 2,
  "offers": [
    {
      "type": "Offer",
      "name": "Adult",
      "price": "9.50",
      "priceCurrency": "GBP"
    },
    {
      "type": "Offer",
      "name": "Junior",
      "price": "4.50",
      "priceCurrency": "GBP"
    }
  ]
}
```

And for a simple case:

```javascript
{
  "type": "Event",
  "identifier": "B2BAD2018-03-01T10:00:00Z",
  "startDate": "2018-03-01T10:00:00Z",
  "endDate": "2018-03-01T11:00:00Z",
  "duration": "PT60M", /* duration converted to ISO spec. Can do this with System.Xml.XmlConvert.ToString(TimeSpan.FromMinutes(ClassDuration)) */
  "inventoryLevel": 1,
  "offers": [
    {
      "type": "Offer",
      "price": "9.50",
      "priceCurrency": "GBP"
    }
  ]
}
```

Note that `"eventStatus": "http://openactive.io/ns#Available"` is still useful in place of `"inventoryLevel": 1` for situations where data publishers do not wish to disclose the granular availability, however this should be considered along with https://github.com/openactive/ns-beta/issues/9 which is solving the same issue.

**Comment by ldodds** [comment]
We're now using remainingUses and maximumUses
