### ISSUE TITLE
Decoupling of FacilityUse and events array

### ISSUE THREAD

**Issue by nickevansuk** [openactive/modelling-opportunity-data#86]
The current plan of having slots embedded in FacilityUse in the `event` array doesn’t work, as there are 700 slots for each FacilityUse instance in the Fusion data (14 days worth of slots). Any changes do a single FacilityUse slot would then trigger resending 700 slots across the wire.

**Comment by ldodds** [comment]
I think this issue is covered by #73, as one of the options covered there is separating out feeds for availability information (including slots)
